### ISSUE TITLE
Can't apply module. Failure creating healthchecks

### ISSUE THREAD

**Issue by diasjorge** [terraform-google-modules/terraform-google-lb-http#103]
I'm getting the following error when applying the module:

Error: "https_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http2_health_check,http_health_check,https_health_check` were specified.

  on .terraform/modules/app_lb/terraform-google-lb-http-4.0.0/modules/dynamic_backends/main.tf line 135, in resource "google_compute_health_check" "default":
 135: resource "google_compute_health_check" "default" {

It seems there's been a change with the google provider that now makes this fail.

The backend protocol in my case is "HTTP".

**Comment by diasjorge** [comment]
A workaround was to comment these lines: https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/modules/dynamic_backends/main.tf#L166-L196

**Comment by diasjorge** [comment]
I can confirm this bug happens with google provider version "3.20.0", if I set the provider version to "3.19.0" the error goes away

**Comment by Dev25** [comment]
Related issue #100 should be fixed in the next provider release

**Comment by diasjorge** [comment]
Thanks!
