### ISSUE TITLE
backend service defaults? - so many nulls 

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-lb-http#109]
Any recommendations on how to not have to repeat `null` everywhere? This is one group for one service, many others look similar and makes the config really long. e.g.:
```
      groups = [
        {
          group                        = data.google_compute_network_endpoint_group.foo.self_link
          balancing_mode               = "RATE"
          capacity_scaler              = null
          description                  = null
          max_connections              = null
          max_connections_per_instance = null
          max_connections_per_endpoint = null
          max_rate                     = null
          max_rate_per_instance        = null
          max_rate_per_endpoint        = 100
          max_utilization              = null
        }
````

**Comment by naseemkullah** [comment]
Furthermore, is it possible to set defaults for these?

https://github.com/terraform-google-modules/terraform-google-lb-http/blob/de140504beaa04c7ffaba595de243ce3f3d89934/variables.tf#L72-L106

**Comment by morgante** [comment]
Unfortunately it's currently impossible to have defaults for objects. This is a Terraform core issue: https://github.com/hashicorp/terraform/issues/19898

**Comment by naseemkullah** [comment]
Thanks for confirming @morgante
