### ISSUE TITLE
Add support for dual-stack IP addresses (both ipv4 and v6)

### ISSUE THREAD

**Issue by kunal-g** [terraform-google-modules/terraform-google-lb-http#112]
Looking at the terraform code in main.tf:
https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/main.tf
there is provision to specify only 1 version of IP addresses via the `ip_version` variable (defaulting to IPv4) in the `google_compute_global_address` resource (https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/main.tf#L42)

Even when the user creates external static IP addresses, there is provision to supply only one such value for the `google_compute_global_forwarding_rule` resources using `local.address`.

In the transitory period of IP versions, it's important to have both IPv4 **and** IPv6 addresses assigned to the load-balancer.

One option to make it configurable would be to accept the variable `ip_version` as a list `ip_versions` where the user can specify what versions of IP addresses they want to deploy - something like:
```
    ip_versions = ["IPv4", "IPv6"]
```
and create the corresponding `google_compute_global_address` resources based on that.
It can default to `["IPv4"]` to retain backwards compatibility.

**Comment by morgante** [comment]
Thanks for highlighting this. I think we could do slightly better by providing two different input variables which would replace the existing `ip_version` and `create_address` variables:

- `create_ipv4_address` (default true)
- `create_ipv6_address` (default false)

**Comment by kunal-g** [comment]
> Thanks for highlighting this. I think we could do slightly better by providing two different input variables which would replace the existing `ip_version` and `create_address` variables:
> 
> * `create_ipv4_address` (default true)
> * `create_ipv6_address` (default false)

Sure, that works too.

However, please also keep in mind the workflow where the user can specify **existing, pre-allocated** IP addresses for both versions.
This is important where updating DNS records may be more difficult - in which case, the user might keep the IP addresses pre-allocated and added to A/AAAA records and use the same ones to assign to the load-balancer. Or, even BYOA (bring-your-own-address) with the cloud router.

**Comment by kunal-g** [comment]
From extensibility and readability perspective, I think the list + map version keeps the structure a bit cleaner.

For example, when `create_address = true`, the `ip_versions` list could be specified as:
```
     ip_versions = [
         "IPv4",
         "IPv6",
         "IPv7",   // future extensions?
    ]
```

For custom, pre-allocated addresses (`create_address = false`), the same scheme works with the map via the `addresses` variable (in lieu of current `address` variable):
```
     addresses = {
        "IPv4": "aa.bb.cc.dd",  // or even some other google_compute_global_address resource self_link/address should work here
        "IPv6": "aa:bb:cc:dd:ee::ff:gg",
        "IPv7": "<SOME_FORMAT>"
    }
```

**Comment by morgante** [comment]
I'm not comfortable with a list as it has no type checking and really isn't the right construct when there are only 2 valid values.

**Comment by kunal-g** [comment]
> I'm not comfortable with a list as it has no type checking and really isn't the right construct when there are only 2 valid values.

Like I said, I'm fine with separate variables per version of IP as well.
Just want to make sure that we also handle the case of pre-allocated addresses as well correctly.

**Comment by morgante** [comment]
Actually, I'm not sure how you're imagining this working? A forwarding rule can only accept a single address (either ipv6 or ipv4) at a time.

**Comment by Dev25** [comment]
FWIW i agree with just using boolean flags to indicate creating ipv4/ipv6 address  `create_ipv4_address`

There are use cases where users may want to bind additional x IPs (to overcome the 15 cert per IP limit) which could be handled by another var, but that's another PR and there is already a workaround: init another module and link to existing url_map

**Comment by kunal-g** [comment]
Here is what I had in mind:
https://github.com/terraform-google-modules/terraform-google-lb-http/pull/114

I just edited the main module code and not templates under `autogen` to try it out and make sure the idea actually works.
I'm not sure I have all the required pieces for all the e2e tests for that case. 🤷‍♂️ 

I have tested it on one of my test projects and seems to bring up the required pieces correctly - the load-balancer gets both the IPv4 and IPv6 addresses assigned.
Tested both the cases - auto-creation of IP addresses as well as pre-allocated IP addresses.
**Caveat:** I didn't actually try sending traffic to the load-balancer to either of the IP addresses - just made sure that terraform runs successfully and infra does indeed come up.

If it looks ok, I can work on the templates and submit a new PR.

**Comment by kunal-g** [comment]
> Actually, I'm not sure how you're imagining this working? A forwarding rule can only accept a single address (either ipv6 or ipv4) at a time.

Yes, that's correct - so, you create multiple forwarding rules - one for each IP address.
I have done a crude impl in #114 - just have a look.

**Comment by kunal-g** [comment]
@morgante did you get a chance to look at the PR #114 ?
