### ISSUE TITLE
Release a version for terraform 0.13

### ISSUE THREAD

**Issue by jeremad** [terraform-google-modules/terraform-google-lb-http#123]
The latest tag (4.2.0) is not compatible with terraform 0.13

**Comment by jeremad** [comment]
https://github.com/terraform-google-modules/terraform-google-lb-http/pull/113

Needs a maintainer review I guess

**Comment by CiolFr** [comment]
The release seems to be stuck @jeremad ?

**Comment by jeremad** [comment]
I am not maintainer. I am a basic user, waiting for a release :)
