### ISSUE TITLE
Unable to use "TCP" health check with http load balancer. 

### ISSUE THREAD

**Issue by mandarmahajan** [terraform-google-modules/terraform-google-lb-http#129]
cannot use TCP health check for http load balancer. Could not find syntax to use tcp_heal_check for http load balancer in this module.  this module expects following code but does not accept tcp_health_check syntax. 

     health_check = {
        check_interval_sec  = 30
        timeout_sec         = 10
        healthy_threshold   = 1
        unhealthy_threshold = 5
        request_path        = "/"        
        port                = 8888
        host                = null
        logging             = null
      }

**Comment by tejasved-q** [comment]
Any update on this issue?
