### ISSUE TITLE
security_policy example

### ISSUE THREAD

**Issue by aaronstutzer** [terraform-google-modules/terraform-google-lb-http#131]
@vktr-brlv can you give an example how to use `security_policy`?
For me terraform only adds a security policy when I change the default value for the `security_policy` variable in in the modules variables.tf

**Comment by aaronstutzer** [comment]
if I set a default security_policy it overwrites the security_policy set per backend. if I don't set a default security_policy the policies set per backend are ignored and the backend would be deployed without security policy.

**Comment by morgante** [comment]
See #130.
