### ISSUE TITLE
v4.4.0: Multiple per-backend security_policy rules defined in backends, but defaults to global var.security_policy anyhow

### ISSUE THREAD

**Issue by jtdelia** [terraform-google-modules/terraform-google-lb-http#133]
Hello,

I'm trying to take advantage of the per-backend security_policy feature but I am not getting the expected results.  I have several rules I want to apply across a large group of backends (30+) but I am only ending up with the default global rule.  A `null` setting does work as I expect (no rule attached), however, I'd expect each `security_policy` in the backend definitions be linked to the appropriate rule rather than the default global rule.  While I have 30+ backends, I'm only trying to attach one of four rules, or no rule at all (`null`).

## Setup:
terraform version 0.13.5
google_provider 3.46.0
google_beta_provider 3.46.0

I have terraform set up as below (abbreviated example).

Top level of the module block is the default security_policy set as:

```
security_policy = google_compute_security_policy.rule1.self_link
```

then in each backend:

```
backend0 = {
  ...
  security_policy = google_compute_security_policy.rule1.self_link
  ...
}
backend1= {
  ...
  security_policy = google_compute_security_policy.rule2.self_link
  ...
}
backend2 = {
  ...
  security_policy = google_compute_security_policy.rule3.self_link
  ...
}
backend3 = {
  ...
  security_policy = null
  ...
}
```

## Result:  
Backends 0,1,2 get `google_compute_security_policy.rule1` attached (not expected), backend3 is set to `null` (no rule attached, as expected).

## Expected result: 
Backends0,1,2 get their assigned rules as defined in each respective backend, backend3 is set to `null` (no rule attached).

Any help is appreciated!  Thank you.

**Comment by morgante** [comment]
This looks like a duplicate of #130, which has a fix in progress: #132.
