### ISSUE TITLE
Version constraint in example code doesn't support Terraform 1.3

### ISSUE THREAD

**Issue by yegle** [terraform-google-modules/terraform-google-lb-http#138]
The version constraint in the example code is `~> 3.1` which is old and doesn't support Terraform 1.3.

**Comment by bharathkkb** [comment]
Hi @yegle 
Thanks for the feedback, it can be updated to the latest. Happy to review a PR. 0.13 support was added in [4.3.0.](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/CHANGELOG.md#430-2020-10-05)
