### ISSUE TITLE
centos-6 image does not exist in multi-backend-multi-mig-bucket-https-lb example

### ISSUE THREAD

**Issue by Dysproz** [terraform-google-modules/terraform-google-lb-http#144]
I was doing Qwiklabs excercie 'HTTPS Content-Based Load Balancer with Terraform' where example multi-backend-multi-mig-bucket-https-lb is used.

However, after running `terraform plan` or `terraform apply` command I get an error **Error: error retrieving image information: googleapi: Error 404: The resource 'projects/centos-cloud/global/images/family/centos-6' was not found, notFound**.

Indeed in GCP images I see that oldest CentOS image is CentOS7 and there's no CentOS6 image. I've tried to manually workaround this problem changing terraform files, but it seems that information about image is gathered from some external bucket.

I'd like to finish lab as it's one of labs required to gather badge of completion of learning path so I'd be grateful for help with workaround for this problem or a fix. :)

**Comment by bharathkkb** [comment]
@Dysproz thanks for the report. This seems to stem from https://github.com/terraform-google-modules/terraform-google-vm/issues/125, so closing this to track it there.
