### ISSUE TITLE
Unable to create Internal HTTPS load balancer - Error creating TargetHttpsProxy: googleapi: Error 404: The resource 'projects/myproject/global/urlMaps/my-app-url-map' was not found, notFound

### ISSUE THREAD

**Issue by jagan1333** [terraform-google-modules/terraform-google-lb-http#161]
Error creating TargetHttpsProxy: googleapi: Error 404: The resource 'projects/myproject/global/urlMaps/my-app-url-map' was not found, notFound

Following are the snippet of terraform scripts,

resource "google_compute_target_https_proxy" "default" {
  project           = var.project
  name              = "${var.app}-https-proxy"
  url_map           = google_compute_region_url_map.urlmap.id
  ssl_certificates  = [google_compute_ssl_certificate.default.self_link]
  ssl_policy        ="${var.project}-ssl-security-policy"
  depends_on = [google_compute_region_url_map.urlmap]
}

resource "google_compute_region_url_map" "urlmap" {
  provider        = google-beta
  project         = var.project
  region          = var.region
  name            = "${var.app}-url-map"
  default_service = google_compute_region_backend_service.default.self_link
}

Everywhere I see only http examples but not https, am I missing something ? Please let me know,

Even I tried by giving self link for url_map in the target proxy block but the same issue, still it is considering global.
URL_MAP Selflink : "https://www.googleapis.com/compute/v1/projects/${var.project}/regions/${var.region}/urlMaps/${var.app}-url-map"

**Comment by morgante** [comment]
It seems you're not using this module. For provider issues please open a bug on the provider.

**Comment by jagan1333** [comment]
@morgante Can you please let me know the link where should I open the issue.

**Comment by morgante** [comment]
@jagan1333 https://github.com/hashicorp/terraform-provider-google/issues
