### ISSUE TITLE
Broken link to v4.5.0

### ISSUE THREAD

**Issue by kumar-dhanagopal** [terraform-google-modules/terraform-google-lb-http#172]
In the https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/README.md#compatibility, the link [v4.5.0](https://registry.terraform.io/modules/terraform-google-modules/-lb-http/google/v4.5.0) is broken.

Is https://registry.terraform.io/modules/GoogleCloudPlatform/lb-http/google/4.5.0 the intended (correct) link?

**Comment by morgante** [comment]
Yes, thanks for catching that.
