### ISSUE TITLE
Testing-related instructions in multi-mig-http-lb example need to be updated

### ISSUE THREAD

**Issue by kumar-dhanagopal** [terraform-google-modules/terraform-google-lb-http#182]
This issue is about the testing-related instructions in the README for the [multi-mig-http-lb](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/examples/multi-mig-http-lb/README.md#test-balancing-to-other-region) example.

After deploying the example, when I ran:
```
TF_VAR_group1_size=0
terraform apply
```
… the following message was displayed:
```
No changes. Your infrastructure matches the configuration.
```

I suspect that’s because the `group1_size` and `group2_size` variables don’t exist in the code. It appears that a single variable `target_size` is used to parameterize the size of both the MIGs in the example.

Note: I was able to test the expected behavior by resizing one of the MIGs through the web console. So there’s no issue with the code and the resources provisioned. This issue is with the instruction in the README to resize MIGs.

**Comment by morgante** [comment]
I suggest we simply remove this section from the repo. I don't think it's all that valuable and apparently has not been maintained. @bharathkkb Thoughts?

**Comment by bharathkkb** [comment]
@morgante yup I agree. This reads more like a tutorial to me than just deploying and verifying the example.

**Comment by kumar-dhanagopal** [comment]
Instead of removing the testing section, consider replacing the resizing steps with the `gcloud` command to resize a MIG:

`gcloud compute instance-groups managed resize NAME --size=0`

If we can make that command 'copy-paste'able by getting the MIG's name from the TF state, that would be awesome.

**Comment by morgante** [comment]
That `gcloud` command will work, but it would lead to an inconsistent Terraform state. I'm not sure we want to promote that.

Do we think this testing section actually substantially aids in learning?

**Comment by kumar-dhanagopal** [comment]
True, using `gcloud` will cause an out-of-band change & inconsistent state. Perhaps we can mention that as a caveat.
I think there's value in including instructions to help users verify/demo the load balancer switching between the regions.

**Comment by morgante** [comment]
Alright, I'm comfortable with using the `gcloud` approach to show how things change. Especially since running terraform again would simply reset to how things were before.

@kumar-dhanagopal Do you mind opening a PR with your suggested change?

**Comment by kumar-dhanagopal** [comment]
Sure @morgante
