### ISSUE TITLE
Cloud Shell version conflict

### ISSUE THREAD

**Issue by kumar-dhanagopal** [terraform-google-modules/terraform-google-lb-http#187]
Cloud Shell in the GCP org that I used for testing has TF v1.0 (at the time of writing this issue), whereas the [multi-mig-http-lb](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/examples/multi-mig-http-lb/versions.tf) example has the version constraint:
```
required_version = "~> 0.13.0"
```
So when I ran `terraform init` from Cloud Shell, an “unsupported TF version” error occurred, as expected.
 
Users who use TF v0.13 (say, from their local host) won’t run into this error. But because the README displays the Cloud Shell button prominently, users might be tempted to try that method.

I was able to work around the error by changing the constraint to:
`required_version = “>= 0.13.0”`

But after changing the version constraint, I ran into a minor issue with the following command in the README:
```
echo http://$(terraform output load-balancer-ip)
```

This command returns: `http://“<address>”` … i.e., the output value is enclosed in double quotes (which appears to be a [breaking change](https://github.com/hashicorp/terraform/issues/27100) since TF v0.14), making the URL unusable. This is a minor issue, but I wanted to report it for completeness.

Suggested fix: Change the version constraint to `>= 0.13.0` and update the `echo http://$(terraform output load-balancer-ip)` step to strip out any double quotes.

**Comment by morgante** [comment]
For root modules, the general recommendation and best practice is to pin to a specific major version. Examples should follow this best practice, so I'm not comfortable with updating this to `>= 0.13.0`. We _can_ upgrade it to `~> 1.0.0` though.

**Comment by imrannayer** [comment]
@kumar-dhanagopal is this still an issue?
