### ISSUE TITLE
Create a module output for the resource "google_compute_url_map" "default"

### ISSUE THREAD

**Issue by denissimonovski** [terraform-google-modules/terraform-google-lb-http#200]
I can work on this if allowed. I want the module to output the link to the url_map it creates because I want a second LB to point to the same url_map. Can I add this?

**Comment by morgante** [comment]
Sure, happy to review a PR.

**Comment by denissimonovski** [comment]
@morgante can you have a look?

**Comment by denissimonovski** [comment]
The PR was merged.
