### ISSUE TITLE
How to update managed SSL certificate on existing load balanacer?

### ISSUE THREAD

**Issue by caddac** [terraform-google-modules/terraform-google-lb-http#207]
I've created a load balancer using this module, setting the `managed_ssl_certificate_domains` value to a list of domain names I want to use SSL for. However now I want to add a new domain. But when applying I get the error 
```
Error when reading or editing ManagedSslCertificate: googleapi: Error 400: The ssl_certificate resource 'projects/myproj/global/sslCertificates/mycert' is already being used by 'projects/myproj/global/targetHttpsProxies/myproxy', resourceInUseByAnotherResource
```

How can I add more domains to this managed cert over time?

**Comment by 27Bslash6** [comment]
Not fixed. Still a thing ...

**Comment by fenos** [comment]
any update? I'm unable to update the manage certificates domain list 😢

**Comment by paulav6** [comment]
bump. Any fixes?

**Comment by seanwillcode** [comment]
Bumping this issue, I'm facing the same problem.
