### ISSUE TITLE
Serverless_negs module: once load balancer is created, the url_map can't be changed

### ISSUE THREAD

**Issue by lukaszsan** [terraform-google-modules/terraform-google-lb-http#213]
Hello

I've faced following issue: after creation of LB using `serverless_negs`, when I try to set up following parameters to:

`url_map        = google_compute_url_map.url-map-explicit.self_link`
`create_url_map = false`
  
 effectively switching the default url map to custom one, I get following error:
 
 `module.load_balancer.module.lb-http-v2.google_compute_url_map.default[0]: Destroying... [id=projects/XYZ/global/urlMaps/XYZ-url-map]
│ Error: Error when reading or editing UrlMap: googleapi: Error 400: The url_map resource 'projects/XYZ/global/urlMaps/XYZ-url-m
ap' is already being used by 'projects/XYZ/global/targetHttpsProxies/XYZ-https-proxy', resourceInUseByAnotherResource`

**Comment by anovis** [comment]
ive had this issue too. i have to remove the backend resource manually and then edit/delete the route. the template should handle this case behind the scenes though

**Comment by mieszkokl** [comment]
In my case manually destroying the default url_map before applying the change helped
```
terraform destroy -target="module.lb-http.google_compute_url_map.default[0]" 
```
