### ISSUE TITLE
Support for Api Gateway serverless-neg

### ISSUE THREAD

**Issue by anovis** [terraform-google-modules/terraform-google-lb-http#214]
Api gateway is is preview as a serverless neg. It would be nice to have this support in this module. 

Not sure if this would require further upstream changes in tf first. 

https://cloud.google.com/api-gateway/docs/gateway-serverless-neg#test_your_load_balancer_configuration

**Comment by demian-uala** [comment]
any update? i need to implement api gateway on load balancer terraform definition
