### ISSUE TITLE
Constraint errors while using multiple modules

### ISSUE THREAD

**Issue by bahag-hammera** [terraform-google-modules/terraform-google-lb-http#216]
Error message:

`Could not retrieve the list of available versions for provider hashicorp/google: locked provider registry.terraform.io/hashicorp/google 3.89.0 does not match configured version constraint >= 3.43.0, >= 3.50.0, ~> 3.53, ~> 3.88, >= 4.0.0, < 4.0.0;`

Problem occurs if you use the "terraform-google-lb-http" because of the versions.tf in:
`.terraform/modules/lb-http/test/setup/versions.tf: version = ">= 3.32, <4.0.0" `

This issue depends on the release of the google provider v4.0.0 
https://github.com/hashicorp/terraform-provider-google/releases

**Comment by yu-iskw** [comment]
Related to https://github.com/terraform-google-modules/terraform-google-lb-http/pull/218

**Comment by yu-iskw** [comment]
@morgante What do you think about the issue? We would like to upgrade the dependent google provider version.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-lb-http/pull/218
