### ISSUE TITLE
Release a new version with support for labels

### ISSUE THREAD

**Issue by willroberts** [terraform-google-modules/terraform-google-lb-http#253]
### TL;DR

Support for labels was added in #250, but the latest release is v6.2.0 from Dec 7 2021. Please release a new version with the latest changes included. Thanks!

**Comment by bharathkkb** [comment]
@willroberts We will need to add an upgrade guide. Tracking in https://github.com/terraform-google-modules/terraform-google-lb-http/issues/254 but happy to review a PR if you have bandwidth

**Comment by willroberts** [comment]
I see that [v6.3.0](https://github.com/terraform-google-modules/terraform-google-lb-http/releases/tag/v6.3.0) has been released. Thanks!
