### ISSUE TITLE
Upgrade guide for v7

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-lb-http#254]
### TL;DR

We may need an upgrade guide using https://www.terraform.io/cli/commands/state/replace-provider for https://github.com/terraform-google-modules/terraform-google-lb-http/pull/251 since are using google-beta provider.

**Comment by apeabody** [comment]
I'm not sure that `terraform state replace-provider will work as desired as "This command will update all resources using the "from" provider, setting the provider to the specified "to" provider.", and I see there is now a mix of resources using the google and google-beta provider.

**Comment by apeabody** [comment]
Closing as no upgrade guide is required as [resources can safely be converted between google and goole beta providers](https://registry.terraform.io/providers/hashicorp/google/3.53.0/docs/guides/provider_versions#converting-resources-between-versions)
