### ISSUE TITLE
Proposing a MR for adding variables for every "computed" name ?

### ISSUE THREAD

**Issue by tpoindessous** [terraform-google-modules/terraform-google-lb-http#268]
### TL;DR

Hi ! We are working on doing some terraform imports from manually-created LB and we will use your TF code in a fork.

I'm trying to convince my team to upstream our changes, for adding variables (with locals) for every name you made "computed". 
Example : https://github.com/terraform-google-modules/terraform-google-lb-http/blob/c5cd0d0f2210cd50581f44fafa1995f512f7d997/main.tf#L106

If we do this MR, would you be "motivated" to review it, or you don't want to touch this code ?

Thanks in advance 

And thanks for your work.

**Comment by bharathkkb** [comment]
@tpoindessous Thanks for the feedback! I am leaning towards not adding a top level variable for every name but we can consider adding a name override object and doing a lookup on that instead? Once tfv1.3 is released [optionals](https://github.com/hashicorp/terraform/releases/tag/v1.3.0-rc1) should allow you to succinctly represent this. WDYT?
