### ISSUE TITLE
Keep a more flat property list

### ISSUE THREAD

**Issue by j-windsor** [terraform-google-modules/terraform-google-lb-http#271]
The required `backends` property is a highly nested object where everything must be explicitly set. In [my configuration](https://github.com/danielgazineu/gcp-terraform/blob/main/modules/http_accessible_mig/main.tf), because I had to set 5 of the values to custom values, I had to specify 45 lines of default values, taking up space in my file.

Keeping a more flat configuration with most properties right on the root of the module make it so you can effectively set defaults, makes the module more compatible with IDE autocomplete tools, and more easily documentable using TF descriptions.

**Comment by bharathkkb** [comment]
@j-windsor Thanks for the feedback. Previously Terraform did not support optionals with complex vars but was recently added in [TF 1.3](https://github.com/hashicorp/terraform/releases/tag/v1.3.0). We will adopt this approach going forward for more succinct configuration options.

**Comment by imrannayer** [comment]
Since we have majority of the values in object optional or comes with default I am going to close this issue.
