### ISSUE TITLE
Missing support for External Backends using HTTPS

### ISSUE THREAD

**Issue by tuminansen** [terraform-google-modules/terraform-google-lb-http#283]
### TL;DR

Unable to create an External Load Balancer (Classic) with External Backend using the HTTPS protocol. 
- Using the `serverless_negs` submodule it was not possible to configure the backend protocol to be HTTPS (https://github.com/terraform-google-modules/terraform-google-lb-http/issues/201)
- Using either no submodule, or the `dynamic_backends` one doesn't allow skipping health check for the backend
- Adding a dummy health check results in an error as well

### Terraform Resources

`GoogleCloudPlatform/lb-http/google`

**Comment by voycey** [comment]
This is linked to this PR as well https://github.com/terraform-google-modules/terraform-google-lb-http/pull/287

**Comment by voycey** [comment]
This has now been implemented in the v7 release
