### ISSUE TITLE
Add support for dynamic compression in serverless_negs

### ISSUE THREAD

**Issue by Lawouach** [terraform-google-modules/terraform-google-lb-http#290]
### TL;DR

Add compression_mode to the serverless_negs module.

### Terraform Resources

```markdown
This is a property of google_compute_backend_service

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#compression_mode
```

### Detailed design

```markdown
Likely like `enable_cdn` we could have something such as:


compression_mode                      = lookup(each.value, "compression_mode", "DISABLED")
```

I'm not sure if `"DISABLED"` is the right default value vs `"AUTOMATIC"`.

**Comment by czka** [comment]
Isn't this a duplicate of https://github.com/terraform-google-modules/terraform-google-lb-http/issues/275 (implemented in https://github.com/terraform-google-modules/terraform-google-lb-http/pull/281)?

**Comment by Lawouach** [comment]
It seems so. I had looked into those but failed to see https://github.com/terraform-google-modules/terraform-google-lb-http/pull/281/files/6e4933af690c74e258e32692ed46686368f09121#diff-010b5d69d284b862dfcf2c30be42076a5c5273c76c3b9a2002cd530eef0f965e

It's probably missing just a release then :)
