### ISSUE TITLE
Registry URL is 404, so cannot access module or documentation

### ISSUE THREAD

**Issue by abower-digimarc** [terraform-google-modules/terraform-google-lb-http#304]
### TL;DR

When I follow the link from the github page to registry.terraform.io, I get a 404 not found.

### Expected behavior

I expected to be able to click the link to registry.terraform.io, and see documentation for the module. Additionally, I expected terraform to resolve the module from that registry. 

### Observed behavior

I see a 404, and cannot view the documentation.

### Terraform Configuration

```hcl
I have not set up terraform config yet due to the previous result.
```

### Terraform Version

```sh
NA
```

**Comment by imrannayer** [comment]
@bharathkkb can you plz check this?

**Comment by imrannayer** [comment]
Fixed
