### ISSUE TITLE
edge_security_policy is not optional

### ISSUE THREAD

**Issue by uap-universe** [terraform-google-modules/terraform-google-lb-http#330]
### TL;DR

The attribute `edge_security_policy` is not optional, although the [upgrade guide](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/v9.0.0/docs/upgrading_to_v9.0.md) says that it is optional.

https://github.com/terraform-google-modules/terraform-google-lb-http/blob/a0ea2acb64ab64a130b7aced40aa25644924499b/variables.tf#L91

### Expected behavior

You do not need to specify a value for the attribute.

### Observed behavior

You are required to specify a value for the attribute.

### Terraform Configuration

```hcl
irrelevant - can be directly observed in the variables.tf
```

### Terraform Version

```sh
Terraform v1.3.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.65.2
+ provider registry.terraform.io/hashicorp/google-beta v4.65.2
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

**Comment by imrannayer** [comment]
@uap-universe Based on following logic do you think it should be set to "" by default?

```
  # To achieve a null backend edge_security_policy, set each.value.edge_security_policy to "" (empty string), otherwise, it fallsback to var.edge_security_policy.
  edge_security_policy = lookup(each.value, "edge_security_policy") == "" ? null : (lookup(each.value, "edge_security_policy") == null ? var.edge_security_policy : each.value.edge_security_policy)
```

**Comment by imrannayer** [comment]
@uap-universe ok I will set it to null local config in PR #333
