### ISSUE TITLE
SSL Certification Output 

### ISSUE THREAD

**Issue by hadi-alnehlawi** [terraform-google-modules/terraform-google-lb-http#344]
### TL;DR

add a new output for the managed ssl certification
```
output  "managed_ssl_certificate" {
  description = "The managed SSL certificates"
  value       = google_compute_ssl_certificate.default.self_link
}
```

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_ssl_certificate.html
```

**Comment by imrannayer** [comment]
@hadi-alnehlawi It seems like u want managed ssl certificate self link but in yous example it is the certificate uploaded to GCP. Can you plz clarify which one u need?
