### ISSUE TITLE
Backend port number is blank after applying plan

### ISSUE THREAD

**Issue by jacohend** [terraform-google-modules/terraform-google-lb-http#38]
The following code results in no backend port for the load balancer:
```
module "gce-lb-http" {
  source            = "github.com/GoogleCloudPlatform/terraform-google-lb-http"
  name              = "group-http-lb"
  target_tags       = ["${var.consul_server_cluster_tag_name}"]
  backends          = {
    "0" = [
      { group = "${module.consul_servers.instance_group}" }
    ],
  }
  backend_params    = [
    # health check path, port name, port number, timeout seconds.
    "/v1/status/leader,api,8500,10"
  ]
}
```
It should result in a backend rule specifying 8500. Only the label, `api` in this case, actually appears in the console after provisioning.

**Comment by aaron-lane** [comment]
Hi @jacohend! I apologize for the extreme delay in responding to your issue. Can you try using the revamped design of #57 to see if it solves your problem?
