### ISSUE TITLE
Latest release is breaking

### ISSUE THREAD

**Issue by noleary1** [terraform-google-modules/terraform-google-lb-http#399]
### TL;DR

Latests (10.1.0) release is breaking. fixing version at 10.0.0 resolves behaviour.

### Expected behavior

terraform plan is returining the observed behaviour.

### Observed behavior

│ Error: Unsupported argument
│ 
│   on .terraform/modules/lb-http/modules/serverless_negs/main.tf line 123, in resource "google_compute_target_https_proxy" "default":
│  123:   server_tls_policy = var.server_tls_policy
│ 
│ An argument named "server_tls_policy" is not expected here.

### Terraform Configuration

```hcl
module "lb-http" {
  source  = "terraform-google-modules/lb-http/google//modules/serverless_negs"
  version = "~> 10.0"

  name    = "${var.environment}-cloud-run-lb-http"
  project = module.project.id

  ssl                             = true
  managed_ssl_certificate_domains = ["xyz123.co.uk"]
  https_redirect                  = true

  backends = {
    default = {
      description = null
      groups = [
        {
          group = google_compute_region_network_endpoint_group.serverless_neg.id
        }
      ]
      enable_cdn = false

      iap_config = {
        enable = true
      }
      log_config = {
        enable = false
      }
    }
  }
}
```

### Terraform Version

```sh
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.75.0
+ provider registry.terraform.io/hashicorp/google-beta v4.75.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

**Comment by imrannayer** [comment]
@noleary1 `server_tls_policy` was part of [4.84.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4840-september-26-2023). Is it possible if you can use provider version 4.84+?

Thanks
