### ISSUE TITLE
Output forwarding rule names

### ISSUE THREAD

**Issue by Zambonilli** [terraform-google-modules/terraform-google-lb-http#408]
### TL;DR

To be able to create alert policies for load balancer metrics the alert policy needs to be filtered on the forwarding_rule_name resource label. Currently the lb-http module does not output the forwarding rule names created.

### Terraform Resources

```markdown
google_compute_global_forwarding_rule -  https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_forwarding_rule#name
```

### Detailed design

```markdown
Create new outputs for IPV4 & IPV6 HTTP and HTTPS forwarding rules.

serverless-negs module
IPV4 HTTP: https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/modules/serverless_negs/main.tf#L31

IPV4 HTTPS: https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/modules/serverless_negs/main.tf#L44

IPV6 HTTP: https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/modules/serverless_negs/main.tf#L68

IPV6 HTTPS: https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/modules/serverless_negs/main.tf#L81
```

### Additional information

Here would be an example of a terraform google_monitoring_alert_policy.conditions.condition_threshold.filter that uses the forwarding rule name in an alert policy.

```
metric.type=\"loadbalancing.googleapis.com/https/request_count\" AND resource.type=\"https_lb_rule\" AND resource.labels.forwarding_rule_name=\"${module.lb-http.ipv4_http_forwarding_rule_name}\
```

**Comment by Zambonilli** [comment]
Here's a workaround as well based for version 10.0.x. You can use the regex.full_match to filter forwarding rules to only those that start with the name value that is passed into lb-http. I set a the name value to a locals so it's only defined once.

```
"metric.type=\"loadbalancing.googleapis.com/https/total_latencies\" AND resource.type=\"https_lb_rule\" AND resource.labels.forwarding_rule_name=monitoring.regex.full_match(\"^${local.lb_http_name}.*\")"
```

**Comment by imrannayer** [comment]
@Zambonilli forwarding rule name is an input. You can reference it without output.

**Comment by Zambonilli** [comment]
Yeah, you're right and I this was all me. I added a random to the end of the forwarding rule name before passing it in. Which made me think the module was adding the random.

Sorry, for the confusion and thanks for the great work on this module!
