### ISSUE TITLE
Support plans?

### ISSUE THREAD

**Issue by amnk** [terraform-google-modules/terraform-google-lb-http#42]
I've come across this useful module, but notices that build is failing for some pipelines. 

So is this module still supported and it is ok to use it?

**Comment by tpoindessous** [comment]
Hi @danisla 

do you still maintain this module ? If not, could you please find another maintainer ?

Thank you !

**Comment by aaron-lane** [comment]
This module is still supported. We're in the process of upgrading it to support Terraform 0.12!
