### ISSUE TITLE
Can't delete an instance groups created by the GKE worker node pool that's in use by a backend service

### ISSUE THREAD

**Issue by rakeshnetsil** [terraform-google-modules/terraform-google-lb-http#48]
I'm using the terraform to manage the GKE cluster setup. I want to update the instance size of the worker nodes that would re-create google_container_node_pol. But that steps failing because below error because instance groups attached with GCP LB backend not detaching by terraform.

oogle_container_node_pool.new_container_cluster_node_pool.0: Error waiting for deleting GKE NodePool:
(1) Google Compute Engine: The instance_template resource 'projects/XXX-XXX-XXXX/global/instanceTemplates/gke-XXX-XXX-us-west-XXXXXX-53369325' is already being used by 'projects/XXXX-XXXX-XXXXX/zones/us-west1-b/instanceGroupManagers/gke-XXXXX-XXXX-us-west-XXXXX-XXXXX-us-west-53369325-grp'

Finally, we have to manually remove the instance groups entries from GCP LB backend, plan and apply again to re-create the node pool with new instance type.

**Comment by aaron-lane** [comment]
@rakeshnetsil I apologize for the extreme delay in responding to this issue.

Can you please share the Terraform configuration which is experiencing this problem? It is not clear to me how your described issue relates to this module.

**Comment by aaron-lane** [comment]
@fbcbarbosa I guess this issue has also affected you. Are you able to provide a configuration to reproduce this issue?

**Comment by morgante** [comment]
Unfortunately I don't think there's any way for us to work around this in the module.
