### ISSUE TITLE
Add support for Terraform 0.12

### ISSUE THREAD

**Issue by ivankorn** [terraform-google-modules/terraform-google-lb-http#51]
Please, note: 
0.12 support for [`managed_instance_group example`](https://github.com/terraform-google-modules/terraform-google-container-vm/tree/master/examples/managed_instance_group) depends on this.
Module to be updated once this task is done. 
Linked: 
- [`module container-vm`](https://github.com/terraform-google-modules/terraform-google-container-vm/issues/28)
- [`terraform-google-managed-instance-group`](https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/issues/42)

**Comment by ivankorn** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-google-lb-http/pull/49

**Comment by ivankorn** [comment]
I'm moving discussion from closed PR #49 [here](https://github.com/terraform-google-modules/terraform-google-lb-http/pull/49#issuecomment-522136833)

@itscaro, thank you for doing a good job on migrating examples! 
Unfortunately your [PR](https://github.com/hyww/terraform-google-lb-http/pull/1) for it uses deprecated MIG template, so `terraform plan` discovers a lot of errors like this 
```
$ terraform plan

Error: Invalid value for module argument

  on main.tf line 65, in module "gce-lb-http":
  65:   target_tags       = [module.mig1.target_tags, module.mig2.target_tags]

The given value is not suitable for child module variable "target_tags"
defined at ../../variables.tf:48,1-23: element 0: string required.


Error: Unsupported block type

  on mig.tf line 20, in data "template_file" "group-startup-script":
  20:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.

```
As @morgante advised [here](https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/issues/42#issuecomment-522050945) the older MIG module is deprecated and we should use  https://github.com/terraform-google-modules/terraform-google-vm/tree/master/modules/mig instead.

@itscaro, unless you're willing to continue your work I'm going to pick up from where you left and proceed with following: 

- Switch MIG and other depdency-modules to TF 0.12 compatible 
- Add strict types for variables
- Remove instances of unnecessary string interpolation from the code base (if any left)
- Remove unnecessary "element" calls  (if any left)
- Update types to number/bool where necessary

Also I'd like to alight this module a bit with [terraform-google-modules](https://github.com/terraform-google-modules)

By adding terraform, bash and white-space linters + doc_generator as a first step in this direction.

**Comment by itscaro** [comment]
@ivankorn please go ahead, I'm going to be off till Sep. Thank you.

**Comment by ivankorn** [comment]
> @ivankorn please go ahead, I'm going to be off till Sep. Thank you.
okay, have a good time off then :)

**Comment by ivankorn** [comment]
> @ivankorn I've been following your work on this. I'm looking for this [internal lb](https://github.com/terraform-google-modules/terraform-google-lb-internal/tree/4e0cfc027ff804d01799d2011f9c6e164b81e372/examples/simple) example
> are you working on this? 

@jtfogarty, not at the moment. But given the update Morgante provided - there are chances for me to pick up some more of lb modules soon. 

> if not, are the items you mentioned above needed to convert this to TF 0.12? Thanks

More than that, I think in addition to those, we should take care of following:
- Add linters and updated helper scripts 
- Standardize tests 
- Switch to new CI 

Just to satisfy immediate functionality needs last two points can probably be addressed out of migration scope.
All the TF modules will likely follow the  [terraform-google-modules](https://github.com/terraform-google-modules) new approach

**Comment by Dev25** [comment]
As part of this 0.12 move is it worth moving straight to using `for_each` (0.12.6+) over the count/index method for managing resources.

https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings

I know other modules are looking to move to using for_each now that is it released e.g. GKE with node-pools, in this module it can be used for backend_services/health_checks

**Comment by morgante** [comment]
@Dev25 Yes, I think that's a good idea. @ivankorn Please switch to using `for_each`.

**Comment by ivankorn** [comment]
> @Dev25 Yes, I think that's a good idea. @ivankorn Please switch to using `for_each`.

`for_each` switch is commited [here](https://github.com/ivankorn/terraform-google-lb-http/commit/26efad92aea00aad9f7899670d843500b87dd988)

For now interface is kept everywhere but [here](https://github.com/ivankorn/terraform-google-lb-http/commit/26efad92aea00aad9f7899670d843500b87dd988#diff-c9ac8098c5ea9d3e6a9a596ff0c512a4L34). That can be easily reverted, but I don't see any sense in keeping at list that. I'm also going to come up with a proposal on more changes as discussed with @aaron-lane on the call today
Since the [PR](https://github.com/terraform-google-modules/terraform-google-lb-http/pull/52) is still in draft I left some comments here and there on interface changes I'd like to make. Followed by migration plan in readme/changelog of course

**Comment by ivankorn** [comment]
@morgante @Dev25 fyi: `for_each` adds a bit to a good amount of entropy on the migration task. 
We're migrating 
- from 0.11 to 0.12
- from `GoogleCloudPlatform/managed-instance-group` to `terraform-google-modules/vm/google//modules/instance_template` and `terraform-google-modules/vm/google//modules/mig` (and adding a number of resources as deps for them)
- from GoogleCloudPlatform/nat-gateway/google to `terraform-google-modules/cloud-nat`

Ad I [reported](https://github.com/terraform-google-modules/terraform-google-lb-http/pull/52#issuecomment-529545564) currently `for_each` has a bug which brakes all multi-backend examples down

cc: @paulpalamarchuk @nick4fake @kopachevsky

**Comment by ivankorn** [comment]
Update: As @morgante advised I pushed `for_each` changes in a separate [branch](https://github.com/ivankorn/terraform-google-lb-http/tree/for_each) aside and [reverted](https://github.com/terraform-google-modules/terraform-google-lb-http/pull/52/commits/fa368c1ab56dd6737a2771f89f33cb97f6c8c024) it back

TF issue ref: https://github.com/hashicorp/terraform/issues/22735
cc: @kopachevsky @nick4fake @paulpalamarchuk @ingwarr @aaron-lane

**Comment by sebastiansirch** [comment]
Hi @ivankorn , 
just want to let you know that I already tested and used your current working state in a project where we needed a Terraform 12 compatible version :-) Works fine.
Best,
Sebastian

**Comment by ivankorn** [comment]
Hi, @sebastiansirch 
Thank you for your feedback! I'm very happy to hear that migration efforts was successful! :)  
I'll notify you once [PR](https://github.com/terraform-google-modules/terraform-google-lb-http/pull/52) get merged, it's under code review which shouldn't take much time. 

Please note: there are #53 and #54 opened for interface changes, so you might need to adjust your side code as well after those get merged. 
Thanks

**Comment by mercuriete** [comment]
@ivankorn

Thank you for this.
I already have a custom version of this module removing everything wasnt working.
I will switch to this official when possible.

Thank you very much.
