### ISSUE TITLE
Combine backend variables

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-lb-http#53]
There are currently three backend-related variables, `backends`, `backend_params`, and `backend_protocol`, [used in combination to configure multiple resources](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/1.0.10/main.tf#L79-L113). This design can be significantly simplified by merging these variables to a single variable of type `list(object)` with appropriate keys.

**Comment by richardmcsong** [comment]
I'd be interested in taking a crack at this. Should I fork off the terraform 0.12 branch, or wait until the branch is merged into master?

**Comment by Dev25** [comment]
As mentioned in the PR https://github.com/terraform-google-modules/terraform-google-lb-http/pull/52#discussion_r323288639 i would be interested in also seeing more options then exposed in this new interface  e.g setting a host header for health checks

**Comment by aaron-lane** [comment]
@richardmcsong you can certainly start work off of the 0.12 branch, though there may be additional commits which will need to be incorporated in to your branch.

**Comment by Dev25** [comment]
@richardmcsong Did you manage to get something up and running yet? I ended up needing to do this last week and have started to use it in production (0.12 + for_each + updated interface/features) that may be of interest. One big change is allowing different types of health checks http/https/http2 along with all the extra var options.

https://github.com/ivankorn/terraform-google-lb-http/compare/acce7ef742...Dev25:for-each


Example backend usage:
```tf
  backends = {
    "default" = {
      protocol    = "HTTP2"
      port_name   = "https"
      timeout_sec = 60
      enable_cdn  = false

      health_check = {
        check_interval_sec  = 5
        timeout_sec         = 5
        healthy_threshold   = 1
        unhealthy_threshold = 3

        http2_health_check = {
          request_path = "/healthz"
          port         = 443
        }
      }

      groups = [
        {
          group                 = data.google_compute_network_endpoint_group.belgium_d.self_link
          balancing_mode        = "RATE"
          max_rate_per_endpoint = 100
          description           = "GKE nginx-ingress"
        },
        {
          group                 = data.google_compute_network_endpoint_group.belgium_c.self_link
          balancing_mode        = "RATE"
          max_rate_per_endpoint = 100
          description           = "GKE nginx-ingress"
        },
      ]
    },
  }
```
