### ISSUE TITLE
Please provide example of multi-cluster container-native load balancing

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-lb-http#59]
As per https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing ... thanks!

**Comment by morgante** [comment]
@naseemkullah As the linked doc explains, GKE load balancers can (and should) be created using Kubernetes objects.

Is there a specific ask you have not accommodated by the kubectl tutorial?

**Comment by naseemkullah** [comment]
Thanks @morgante, I am new to GLBC (used regional LB fronted nginx-ingress until now) and as my org is working on distributing services globally we want to use the GLBC LB. 

Terraform is what we use to deploy GCP resources so I thought it would have to be created via TF.
My mistake!

**Comment by morgante** [comment]
No worries! You should be able to use the Kubernetes resources directly (the GKE controller handles creating the GCP resources for you).

**Comment by naseemkullah** [comment]
Great, thanks! That saved me a lot of messing around. :)

**Comment by naseemkullah** [comment]
@morgante My issue is I want a multi cluster ingress defined declaratively, is this possible without using Terraform?

https://github.com/kubernetes/ingress-gce/issues/794

**Comment by morgante** [comment]
Got it, for that case you might want to look at autoneg: https://github.com/GoogleCloudPlatform/gke-autoneg-controller

**Comment by Dev25** [comment]
You could this today via [standalone NEGs](https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg) + this module with some tweaks (support `max_*_per_endpoint` backend group vars) + using the NEG datasource

I do have a large/breaking PR that includes NEG support https://github.com/terraform-google-modules/terraform-google-lb-http/pull/57 which includes an example of doing that.

You could make a smaller PR that just includes the minimum changes (those backend vars) to support NEGs

**Comment by naseemkullah** [comment]
> Got it, for that case you might want to look at autoneg: https://github.com/GoogleCloudPlatform/gke-autoneg-controller

This looks really interesting @morgante but I am confused as how to actually deploy it and what seperate steps need to be taken in order to have a multi-cluster ingress routing to NEGs in multiple clusters.

Is this the correct workflow?

1. deploy the autoneg-controller
2. create an LB, create backend services <-- Terraform
3. annotate services in clusters so autoneg-controller can map them to the TF created backend services of the TF created LB ?

**Comment by naseemkullah** [comment]
> You could this today via [standalone NEGs](https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg) + this module with some tweaks (support `max_*_per_endpoint` backend group vars) + using the NEG datasource
> 
> I do have a large/breaking PR that includes NEG support #57 which includes an example of doing that.
> 
> You could make a smaller PR that just includes the minimum changes (those backend vars) to support NEGs

That's excellent @Dev25 

May I ask, once your PR goes through would the workflow would be something like:

1. Use TF to deploy GKE
2. Use whatever method to deploy your app to GKE, including the standalone NEG annotated service
3. Go back to TF and use it to deploy this module, with the new standalone NEG as datasource

?

**Comment by Dev25** [comment]
Yes that would be correct @naseemkullah , once you create the NEG service inside GKE you can figure out the compute engine NEG name (there is a `cloud.google.com/neg-status` annotation on the kubernetes service) and use that in TF/this module.

**Comment by naseemkullah** [comment]
Thanks for clarifying, I look forward to your PR being merged!
