### ISSUE TITLE
Instance groups from multi zone cluster

### ISSUE THREAD

**Issue by hawksight** [terraform-google-modules/terraform-google-lb-http#6]
Please correct me if wrong, but the readme basically takes the first instance group from an existing cluster and configures the load balancer to use this as the backend in a backend service.
*Note* - I was following the example [here](https://github.com/GoogleCloudPlatform/terraform-google-examples/tree/master/example-lb-https-gke) as a basis to work from.

As is, will this module support multi zone clusters? i.e. a cluster that has say 3 instance groups. Given the output from the google_container_cluster is a list [here](https://www.terraform.io/docs/providers/google/r/container_cluster.html#attributes-reference), im not sure how I can go about iternating over that particular list within the `backends` segment of this load balancer. i.e.

```
  backends = {
    "0" = [
      {
        # Each node pool instance group should be added to the backend.
        group = "${var.backend}"
      },
    ]
  }
```

I could manually add numbers from the list, eg. if the output was called: `TARGET_GROUP_URLS`
I could do the following:
```
  backends = {
    "0" = [
      {
        # Each node pool instance group should be added to the backend.
        group = "${var.TARGET_GROUP_URLS[0]}"
        group = "${var.TARGET_GROUP_URLS[1]}"
        group = "${var.TARGET_GROUP_URLS[2]}"
      },
    ]
  }
```

However if my cluster may have many node pools, I may not know the end number of target groups. So the above would work but only if I know exactly the number of URLS to expect.

Is there any way to populate recursively using count based on the length of the the var?
Or am I missing something and I don't need to provide all the instance group urls specifically?

**Comment by mkozjak** [comment]
Any info on this one?

**Comment by aaron-lane** [comment]
Hi @hawksight and @mkozjak. Thank you for your interest in the project! I apologize for the extreme delay in responding.

You can specify multiple backend objects for each index in the `backends` input, but each backend object can only specify one group. I think it should be possible to dynamically build the `backends` input using [for expressions](https://www.terraform.io/docs/configuration/expressions.html#for-expressions).

**Comment by hawksight** [comment]
Thanks @aaron-lane - I've been using this module as the basis of my own for a long time.
Being able to loop through the backends so that the number of them is not longer hard coded is now possible for creation using a `dynamic` block.

Also to answer my own original question - yes this module will support multi zone clusters and cluster with multiple node pool. You just have to ensure you get the complete list of instance_groups in order to populate the `group` value of the `backends` input of this module.

The same limitation seems to apply that you will need to know up front how many instance_groups your going to have. In reality I find I do know as we are fairly static in the group respect. Your mileage may vary.

I just checked through this module's recent code for your 0.12 TF support where you use a dynamic block [here](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/main.tf#L89-L102) similar to what I have in my own module

```
  dynamic "backend" {
    for_each = var.backend_group_list
    content {
      group = backend.value
      // adding null values otherwise reapplication fails
      balancing_mode               = null
      capacity_scaler              = null
      description                  = null
      max_connections              = null
      max_connections_per_instance = null
      max_rate                     = null
      max_rate_per_instance        = null
      max_utilization              = null
    }
  }
```

Where `backend_group_list` = `data.google_container_cluster.information.instance_group_urls`.
I set null here so that the default apply without having to know them. 

Have you seen any problems updating load balancers after they are initially built? I find my code currently works to build, but `tf apply` on a plan once the `backend_service` resources are built comes back with errors. I've got an issue open [here](https://github.com/terraform-providers/terraform-provider-google/issues/3937) but wondered if you might have come across the errors I've seen when updating the module?

**Comment by aaron-lane** [comment]
I am not familiar with the issue that you're describing but I have not worked extensively with this module. If you think there is work needed on the module after https://github.com/terraform-providers/terraform-provider-google/issues/3937 is addressed then please do open a new issue here.

I'm closing this issue since you've managed to answer your own question. :smile:
