### ISSUE TITLE
Allow creation of LB with backend services that are not tied to any actual IG or NEG

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-lb-http#63]
I am interested in using https://github.com/GoogleCloudPlatform/gke-autoneg-controller which only requires that backend services be created, but they need not any associated IGs or NEGs (though they could be of one of those types) as the autoneg-controller will handle that.

I would like to confirm that it is indeed possible via this module to achieve the creation of a GCLB with backend services not associated to any IGs or NEGs.

Thanks in advance.

**Comment by morgante** [comment]
@naseemkullah The module might not *currently* allow that, but it's a scenario I'm also interested in and we will work to make sure there's a possible solution available.

**Comment by naseemkullah** [comment]
Thanks for confirming @morgante I've adjusted the issue title accordingly.

**Comment by Dev25** [comment]
FYI (at least tested with my PR but i don't see why it wouldn't work in master either) you can create a backend with no `groups` provided using this module.

**Comment by naseemkullah** [comment]
That's great @Dev25 !!
