### ISSUE TITLE
Update providers

### ISSUE THREAD

**Issue by Nayels** [terraform-google-modules/terraform-google-lb-http#70]
The provider constraint now restricts terraform to only use `2.7.0`. Which is quite old now (21 may 2019)
```
terraform {
  required_version = "~> 0.12.0"
  required_providers {
    google      = "~> 2.7"
    google-beta = "~> 2.7"
  }
}
```
Can we update the bundle to use at least 2.20?

**Comment by aaron-lane** [comment]
Hi @Nayels!

The constraints as defined set a minimum requirement of 2.7 and a maximum requirement of less than 3.0.

**Comment by Nayels** [comment]
Sorry for the late reply @aaron-lane. The fact I didn't think about the `>` boggles my mind 🤦🏻‍♂️
Closing the issue.
