### ISSUE TITLE
Feature to ignore changes to backend services

### ISSUE THREAD

**Issue by artazar** [terraform-google-modules/terraform-google-lb-http#74]
Hi,

I am using the Google LB Terraform module to create an LB with empty backend services that get automatically populated later on by Google's AutoNEG feature: https://github.com/GoogleCloudPlatform/gke-autoneg-controller

The issue here is that backends are created outside of terraform, so when this is done, the next run of Terraform plan intends to destroy them.

It would be nice to have an optional variable for the module to enable ignore_changes for backends specifically to make use of this feature.

Thanks!

TF configuration in use:

	module "global-loadbalancer" {
	  source  = "GoogleCloudPlatform/lb-http/google"
	  version = "3.0.0"
	  project = var.project_id
	  name    = "global-loadbalancer"

	  ssl         = true
	  private_key = file("key")
	  certificate = file("cert")

	  firewall_networks = ["c0"]
	  firewall_projects = [var.host_project_id]

	  target_tags = []

	  url_map        = google_compute_url_map.url-map.self_link
	  create_url_map = false

	  // We create empty backends to populate them automatically with autoneg feature
	  // https://github.com/GoogleCloudPlatform/gke-autoneg-controller
	  backends = {

		"frontendapi" = {
		  description                     = null
		  protocol                        = "HTTP"
		  port                            = 8080
		  port_name                       = "http"
		  timeout_sec                     = 10
		  connection_draining_timeout_sec = null
		  enable_cdn                      = false
		  health_check                    = local.health_check
		  groups = []
		}
	  }
	}

**Comment by morgante** [comment]
I agree this could be quite useful and should be a use case we support.

However, instead of directly exposing an option to ignore changes and using it together with an empty groups list, I think we might want to automatically ignore changes on any backend without any groups.

**Comment by jamiedick** [comment]
Hi - would it be possible to provide a better example of how to accomplish this?  I have tried a few different ways and cannot get the dymanic backend submodule to work for me.  Either terraform wants to remove my backend services added outside the scope of TF (by autoneg), or terraform complains that I'm not providing the expected values in the `backend` var.

```
module "load_balancer" {
  source  = "GoogleCloudPlatform/lb-http/google"
  version = "~> 5.1"

  name    = "app
  project = var.project_id

  backends = {
    default = {
      description                     = null
      protocol                        = "HTTPS"
      port                            = 443
      port_name                       = "https"
      timeout_sec                     = 30 # 10
      connection_draining_timeout_sec = 0
      enable_cdn                      = false
      security_policy                 = null
      session_affinity                = null
      affinity_cookie_ttl_sec         = null
      custom_request_headers          = null
      custom_response_headers         = null

      health_check = {
        check_interval_sec  = 15
        timeout_sec         = 15
        healthy_threshold   = 1
        unhealthy_threshold = 2
        request_path        = "/api/health"
        port                = 443
        host                = null
        logging             = true
      }

      log_config = {
        enable      = true
        sample_rate = 1.0
      }

      groups = null 

      groups = [
        {
          group                        = null
          balancing_mode               = null
          capacity_scaler              = null
          description                  = null
          max_connections              = null
          max_connections_per_instance = null
          max_connections_per_endpoint = null
          max_rate                     = null
          max_rate_per_instance        = null
          max_rate_per_endpoint        = null
          max_utilization              = null
        },
      ]

    groups = []

      iap_config = {
        enable               = false
        oauth2_client_id     = ""
        oauth2_client_secret = ""
      }
    }
  }
}
```

none of the above configurations work.  In your example, you cite using the following config:
```      
groups = [
        {
          # Each node pool instance group should be added to the backend.
          group                        = var.backend
          balancing_mode               = null
          capacity_scaler              = null
          description                  = null
          max_connections              = null
          max_connections_per_instance = null
          max_connections_per_endpoint = null
          max_rate                     = null
          max_rate_per_instance        = null
          max_rate_per_endpoint        = null
          max_utilization              = null
        },
      ]
```
but im not sure what to provide for that var, since i dont have a true backend to provide to this.  Any advice you can provide would be greatly appreciated.
