### ISSUE TITLE
Relax version constraints 

### ISSUE THREAD

**Issue by danielezer** [terraform-google-modules/terraform-google-lb-http#75]
Currently, the google provider required is:
```
google      = "~> 2.15"
google-beta = "~> 2.15"
```
Which is pretty old, it was released on Sep 18, 2019.
The latest version is already 3.3, can you please upgrade the versions.tf to use the latest version?

**Comment by beatcracker** [comment]
I've hit this issue to: I need to use newer version of the `google-beta` provider which supports `IAM Conditions`. Unfortunately, I can't do that because of the constraints in the module.

The official recommendation for modules is to use `>=`

> [Specifying Required Provider Versions](https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions)
>
> Re-usable modules should constrain only the minimum allowed version, such as `>= 1.0.0`. This specifies the earliest version that the module is compatible with while leaving the user of the module flexibility to upgrade to newer versions of the provider without altering the module.

**Comment by morgante** [comment]
We intentionally pin our versions pessmistically to prevent unexpected errors, but I would be happy to review/accept a PR which changes the version constraint to `>= 2.15, <4.0` *and* updates the version used in tests.

**Comment by danielezer** [comment]
@morgante @Dev25 I think you missed one of the version constraints...
In `test/setup/versions.tf` I can still see the following block:
```
provider "google" {
  version = "~> 2.15"
}

provider "google-beta" {
  version = "~> 2.15"
}
```
This causes terraform init to fail with this error:
```
Error: provider.google-beta: no suitable version installed
  version requirements: "~> 2.15,~> 2.15"
  versions installed: "3.6.0"

Error: provider.google: no suitable version installed
  version requirements: "~> 2.15,~> 2.15"
  versions installed: "3.6.0"
```

**Comment by danielezer** [comment]
I think this issue should be re-opened

**Comment by ryan-jan** [comment]
Me too, this is such a pain and goes directly against [Terraform's recommendations](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#terraform-core-and-provider-versions)!!

> Reusable modules should constrain only their minimum allowed versions of Terraform and providers, such as >= 0.12.0. This helps avoid known incompatibilities, while allowing the user of the module flexibility to upgrade to newer versions of Terraform without altering the module.
