### ISSUE TITLE
log_config can't be disabled

### ISSUE THREAD

**Issue by diasjorge** [terraform-google-modules/terraform-google-lb-http#92]
I'm tryng to create a load balancer and set:

```
log_config {
  enable = false
  sample_rate = null
}
```

The configuration doesn't work correctly as it is always set to enable->true sample_rate->1

I can see this in the logs

```
2020-03-18T12:45:50.787+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.13.0_x5:   },
2020-03-18T12:45:50.787+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.13.0_x5:   "logConfig": {
2020-03-18T12:45:50.787+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.13.0_x5:     "enable": true,
2020-03-18T12:45:50.787+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.13.0_x5:     "sampleRate": 1
2020-03-18T12:45:50.787+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.13.0_x5:   },
```

```
2020/03/18 12:45:50 [WARN] Provider "registry.terraform.io/-/google-beta" produced an unexpected new value for module.app_lb.google_compute_backend_service.default["default"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .log_config[0].enable: was cty.False, but now cty.True
      - .log_config[0].sample_rate: was null, but now cty.NumberIntVal(1)
```

**Comment by morgante** [comment]
Can you try the 4.0 version and confirm if this is still breaking?

**Comment by diasjorge** [comment]
Hi @morgante I've tried with version 4.0 and it's still a problem.
I was debugging and it seems this bug might be in the provider. Do you know any maintainers for it? I don't see a way to reach them

**Comment by morgante** [comment]
@diasjorge You can file an issue here - https://github.com/terraform-providers/terraform-provider-google/issues

**Comment by caoilte** [comment]
Somebody posted a work-around on the underlying providers bug issue that might be worth adopting in this module?

https://github.com/hashicorp/terraform-provider-google/issues/6260#issuecomment-952770590
