### ISSUE TITLE
4.0 upgrade nodes about log_config are wrong

### ISSUE THREAD

**Issue by acdha** [terraform-google-modules/terraform-google-lb-http#94]
https://github.com/terraform-google-modules/terraform-google-lb-http/releases/tag/v4.0.0 says

> You must now specify log_config for each backend service. Use `log_config = null` to use the default.

The module expects a map so this will fail:

```
Error: Invalid function argument

  on .terraform/modules/gce-lb-http/terraform-google-lb-http-4.0.0/main.tf line 124, in resource "google_compute_backend_service" "default":
 124:     enable      = lookup(lookup(each.value, "log_config", {}), "enable", true)
    |----------------
    | each.value is object with 12 attributes

Invalid value for "inputMap" parameter: argument must not be null.


Error: Invalid function argument

  on .terraform/modules/gce-lb-http/terraform-google-lb-http-4.0.0/main.tf line 125, in resource "google_compute_backend_service" "default":
 125:     sample_rate = lookup(lookup(each.value, "log_config", {}), "sample_rate", "1.0")
    |----------------
    | each.value is object with 12 attributes

Invalid value for "inputMap" parameter: argument must not be null.
```

**Comment by morgante** [comment]
If you set `log_config = {}` does that work?

**Comment by diasjorge** [comment]
Setting log_config = {}, causes an issue where the changes are "not stable" meaning they will try to be applied every time you run `terragrunt apply` even when previously applied

**Comment by morgante** [comment]
@diasjorge That sounds like a provider issue. Could you file an issue [there](https://github.com/hashicorp/terraform-provider-google/issues)?

**Comment by diasjorge** [comment]
There’s already an issue. https://github.com/hashicorp/terraform-provider-google/issues/6260
