### ISSUE TITLE
option to provision google managed ssl cert(s)

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-lb-http#96]
It seems like there is none. In order to integrate Google Managed SSL Certs with this module, they must be created separately. Not a big deal but wondering if it would be easily embeddable into the module

**Comment by anuragbeniwal** [comment]
+1 for this feature request

**Comment by morgante** [comment]
This does seem like a useful addition. I'd be happy to review a PR.

**Comment by ahmetb** [comment]
This will be almost a requirement for most serverless GCLB users (Cloud Run, GCF etc).

**Comment by naseemkullah** [comment]
> This will be almost a requirement for most serverless GCLB users (Cloud Run, GCF etc) as that user persona does not purchase certificates.

Today they can create managed certs via https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_managed_ssl_certificate and then feed them into this lb module, but managing them within the module would be great.

**Comment by ahmetb** [comment]
That's actually a good point.

**Comment by ahmetb** [comment]
I've sent a small patch at #136. The conditionals are getting a bit out of control. PTAL and give feedback.
