### ISSUE TITLE
 ssl_certificates - ssl & use_ssl_certificates

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-lb-http#97]
Is it ever desirable to set `ssl_certificates`  but keep `use_ssl_certificates` to `false`?
Is it ever desirable to set `ssl_certificates`  but keep `ssl` to `false`?

If not, it might be best to implicitly enable `ssl` and `use_ssl_certificates` if `ssl_certificates` is set.

**Comment by naseemkullah** [comment]
Furthermore, maybe `ssl` could implicitly be set to true as well, when `ssl_certificates` is set.

i.e. a better experience than:

```yaml
  ssl            = true
  ssl_certificates = [
    google_compute_managed_ssl_certificate.domain_dot_io.self_link,
    google_compute_managed_ssl_certificate.domain_dot_com.self_link
  ]
  use_ssl_certificates = true
```

would be:

```yaml
  ssl_certificates = [
    google_compute_managed_ssl_certificate.domain_dot_io.self_link,
    google_compute_managed_ssl_certificate.domain_dot_com.self_link
  ]
```

**Comment by morgante** [comment]
I agree with consolidation, suggest we test these combinations.
